#!/bin/bash

#--- small script to sort all the CVAO dat files into one file.
#---clean up directory 
rm -f combined.csv 
rm -f sorted.csv

SCRIPTDIR=$(dirname $0)

#---Use pandas to pull all the csv files together in one file
python $SCRIPTDIR/combined.py $1

#---create a new file with all the data sorted in date order.
cat combined.csv |sort |uniq > sorted.csv

#---delete the unsorted file
rm combined.csv

#split into yearly files
python $SCRIPTDIR/split_by_year.py

#clean up
rm sorted.csv



